### ISSUE TITLE
Can't register.  It appears that the table auth_user doesn't exist

### ISSUE THREAD

**Issue by Skyshayde** [raymestalez/fictionhub#1]
Error is below

relation "auth_user" does not exist
LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
                               ^

I haven't used raw sql in a bit, so i'm a bit rusty but I think that the table auth_user doesn't exist.

**Comment by raymestalez** [comment]
Thanks for catching that! 
Fixed.
